### PR TITLE
Fix object and array types not supported in type array form (#59)

### PR DESCRIPTION
**Pull request by trevorr**
Recognize object and array as built-in types in string form
Default array item type to any in expanded and canonical form

### CODE REVIEW

**Review by ForsakenHarmony — APPROVED** [review]
LGTM

**Comment by ForsakenHarmony** [comment]
we can merge this if you fix the conflicts

and maybe add `or 'any'` to `2.ii.a` in Expanded Form and `3.i` in Canonical Form (`algorithms.md`)

**Comment by trevorr** [comment]
I fixed the conflicts and updated `algorithms.md`.

Would you mind doing a release after this is merged? I'm trying to get raml2html working, so I'll need to bump the version of this dependency in raml2obj. It's still using `0.0.15`. 🙁

**Comment by jstoiko** [comment]
@trevorr just released `v0.2.2`. thanks again for those 2 PRs!

**Pull request merged**
