### PR TITLE
Preserve non-functional facets in minType union handling

### LINKED ISSUE #88: minType union handling does not preserve non-functional facets
Consider the following types:

```js
  T1: {
    displayName: 'T1',
    type: 'object'
  },
  T2: {
    displayName: 'T2',
    type: 'T1'
  },
  T5: {
    displayName: 'T5',
    type: ['T1|T2'],
    properties: {
      kind: 'string'
    }
  }
```

Ideally, the canonical form of `T5` would preserve non-functional facets like `displayName`:

```js
  T5: {
    displayName: 'T5',
    type: 'union',
    anyOf: [{
      displayName: 'T1',
      type: 'object',
      properties: {
        kind: {
          type: 'string',
          required: true
        }
      },
      additionalProperties: true
    }, {
      displayName: 'T2',
      type: 'object',
      properties: {
        kind: {
          type: 'string',
          required: true
        }
      },
      additionalProperties: true
    }]
  }
```

However, the current implementation of `minType` simply uses `T5` as a sub-type to recursively apply to the super-type alternatives `T1` and `T2`. This results in the non-functional facets of `T5` overwriting those of the alternatives and not being applied to the top-level type:

```js
  T5: {
    type: 'union',
    anyOf: [{
      displayName: 'T5',
      type: 'object',
      properties: {
        kind: {
          type: 'string',
          required: true
        }
      },
      additionalProperties: true
    }, {
      displayName: 'T5',
      type: 'object',
      properties: {
        kind: {
          type: 'string',
          required: true
        }
      },
      additionalProperties: true
    }]
  }
```

In the `minType` union cases where one of the types is not a union (7.3 and 7.5), I think it would be better to apply the non-functional facets to the computed/top-level type and apply only the functional facets recursively (7.7). Functional vs non-functional facets are loosely defined in the RAML spec.

### PR DESCRIPTION
**Pull request by trevorr**
Fixes #88

### CODE REVIEW

**Comment by trevorr** [comment]
@jstoiko @ForsakenHarmony What do you think about this PR? It's critically important to my raml2html work, as the existing canonicalization rules lose important information when an object type inherits from a union. It takes an unprecedented approach to split facets into functional and non-functional in this limited case, but it was the best way I could see to handle the issue. I think the example in the issue (#88) illustrates the problem pretty clearly.

**Comment by jstoiko** [comment]
@antoniogarrote: would you mind taking a look at this issue/PR as well? The rationale makes sense to me but I have a doubt since I think the RAML spec says that types can override properties inherited from unions.

**Comment by trevorr** [comment]
I think this change does still allow (object) properties from unions to be overridden (as well as functional facets like restrictions). It just prevents overriding of non-functional facets like `displayName` and `description` on union alternatives, which it assumes belong to the union type itself, and not its alternatives.

**Review by ForsakenHarmony — APPROVED** [review]

**Comment by antoniogarrote** [comment]
Makes sense to me. 
The algorithm really cares about the 'functional facets' what to do with the non functional ones is really use case dependent. The RAML spec as far as I know doesn't provide much clarity here.

In AMF, for example, we are also preserving some of them, like the name, in the resolution algorithm.

**Comment by jstoiko** [comment]
in that case would it make sense to 
make preserving non-functional facets an option?

this would have the added benefit of not introducing any breaking changes and avoid having to bump the major although we should really bump to 1.x at some point but that’s another story.

**Comment by trevorr** [comment]
I don't think this change is likely to break anyone, since minType union handling was only recently fixed (v0.2.6) to handle these constructs. For instance, if I revert to v0.2.5, canonicalization of `T3` yields this (which certainly isn't canonical):

```js
  T3: {
    displayName: 'T3',
    type: 'union',
    anyOf: [{
      displayName: 'T2',
      type: {
        displayName: 'T1',
        type: 'object',
        additionalProperties: true
      }
    }]
  }
```

And canonicalization of `T4` fails with `Error: incompatible types: [undefined, [object Object]]`.

If an option were to be added, it's hard to imagine how it would be explained to users. One would really have to understand the algorithms pretty well to understand the effect.

**Review by jstoiko — APPROVED** [review]
merging this since it is unlikely to break anything

**Pull request merged**
